chore: add node_version file, update script logic (#12)
* chore: add node-version file to manage w/ FNM

* chore: update autocompletions and omz config

* chore: update script

* chore: update FMN settings and add zsh auto-complete horsepower (#11)

* chore: add node-version file to manage w/ FNM

* chore: update autocompletions and omz config

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -27,27 +27,27 @@ fail () {
   exit
 }
 
-setup_gitconfig () {
-  if ! [ -f git/gitconfig.local.symlink ]
-  then
-    info 'setup gitconfig'
+# setup_gitconfig () {
+#   if ! [ -f git/gitconfig.local.symlink ]
+#   then
+#     info 'setup gitconfig'
 
-    git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]
-    then
-      git_credential='osxkeychain'
-    fi
+#     git_credential='cache'
+#     if [ "$(uname -s)" == "Darwin" ]
+#     then
+#       git_credential='osxkeychain'
+#     fi
 
-    user ' - What is your github author name?'
-    read -e git_authorname
-    user ' - What is your github author email?'
-    read -e git_authoremail
+#     user ' - What is your github author name?'
+#     read -e git_authorname
+#     user ' - What is your github author email?'
+#     read -e git_authoremail
 
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
+#     sed -e "s/AUTHOR_NAME/$git_authorname/g" -e "s/AUTHOR_EMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
 
-    success 'gitconfig'
-  fi
-}
+#     success 'gitconfig'
+#   fi
+# }
 
 
 link_file () {
@@ -139,20 +139,20 @@ install_dotfiles () {
   success 'dotfiles installed'
 }
 
-setup_gitconfig
+# setup_gitconfig
 install_dotfiles
 
 # If we're on a Mac, let's install and setup homebrew.
-if [ "$(uname -s)" == "Darwin" ]
-then
-  info "installing dependencies"
-  if source bin/dot > /tmp/dotfiles-dot 2>&1
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
-fi
+# if [ "$(uname -s)" == "Darwin" ]
+# then
+#   info "installing dependencies"
+#   if source bin/dot > /tmp/dotfiles-dot 2>&1
+#   then
+#     success "dependencies installed"
+#   else
+#     fail "error installing dependencies"
+#   fi
+# fi
 
 echo ''
-success 'All installed!'
+success 'All installed! Now run `script/install` to complete the setup.'
